# Generated by Django 5.0 on 2023-12-17 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('InProgress', 'InProgress'), ('Completed', 'Completed')], max_length=35, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.department')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientHasAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('allergy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.allergy')),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='PatientHasDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.appointment')),
                ('diagnosis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.diagnosis')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('floor', models.CharField(max_length=100)),
                ('isAvailable', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('NURSE', 'NURSE'), ('DOCTOR', 'DOCTOR'), ('RECEPTIONIST', 'RECEPTIONIST')], max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('shift', models.CharField(choices=[('9AM-5PM', '9AM-5PM'), ('6PM-12AM', '6PM-12AM'), ('12AM-6AM', '12AM-6AM')], max_length=35)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConditionCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heigth', models.CharField(max_length=5)),
                ('weigth', models.CharField(max_length=5)),
                ('urgency', models.CharField(choices=[('Yes', 'Yes'), ('Sometimes', 'Sometimes'), ('No', 'No')], max_length=15)),
                ('abnormal_breathing', models.CharField(choices=[('Yes', 'Yes'), ('Sometimes', 'Sometimes'), ('No', 'No')], max_length=15)),
                ('smokes', models.CharField(choices=[('Yes', 'Yes'), ('Sometimes', 'Sometimes'), ('No', 'No')], max_length=15)),
                ('drinks', models.CharField(choices=[('Yes', 'Yes'), ('Sometimes', 'Sometimes'), ('No', 'No')], max_length=15)),
                ('has_headache', models.CharField(choices=[('Yes', 'Yes'), ('Sometimes', 'Sometimes'), ('No', 'No')], max_length=15)),
                ('mental_state', models.CharField(choices=[('Stable', 'Stable'), ('Mildly distressed', 'Mildly distressed'), ('Moderately distressed', 'Moderately distressed'), ('Severely distressed', 'Severely distressed'), ('Acutely psychotic', 'Acutely psychotic')], max_length=50)),
                ('heart_rate', models.CharField(max_length=20)),
                ('blood_presure', models.CharField(max_length=20)),
                ('temperature', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.appointment')),
                ('nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.staff')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_appts', to='app.staff'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='nurse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_appts', to='app.staff'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='receptionits',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recep_appts', to='app.staff'),
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgery_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('InProgress', 'InProgress'), ('Completed', 'Completed')], max_length=35, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.appointment')),
                ('nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_surgery', to='app.staff')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.room')),
                ('surgeon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgeon_surgery', to='app.staff')),
            ],
        ),
    ]
